### ISSUE TITLE
missing binaries in some builders

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/builders#37]
1. In the base image
  https://github.com/threefoldtech/builders/blob/831fe8a10ef24d8aafe44ae09b9aeb5fa6de3888/builders/4_base/Dockerfile#L14
2. In the 3bot image
  https://github.com/threefoldtech/builders/blob/831fe8a10ef24d8aafe44ae09b9aeb5fa6de3888/builders/9_3bot/Dockerfile#L10

The Docker build failed because of missing files in these two Add commands. 
To skip the zinit one I downloaded the binary from the release instead 
  ```docker
  RUN apk add wget && \
    wget https://github.com/threefoldtech/zinit/releases/download/v0.2.5/zinit -O /bin/zinit  && \
    chmod +x /bin/zinit
  ```

But for the second one, I can't figure out what the required nats bins. is it only the server binary? it can be downloaded from [here](https://docs.nats.io/running-a-nats-service/introduction/installation#downloading-a-release-build). Or something else

**Comment by despiegk** [comment]
thats not the right way, its build in the beginning of the flow from source and added in the image
don't do above

it means something was wrong for you in previous step, try again please
