### ISSUE TITLE
zdb builder not working

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/builders#54]
<img width="1411" alt="image" src="https://github.com/threefoldtech/vbuilders/assets/6021844/858341cd-5ecf-4ff6-916d-a5448e3a1883">

see code/github/threefoldtech/builders/builders/core/zdb/zdb.v

> branch crystallib: development_process

**Comment by maxux** [comment]
Should be fixed on zdb repository, can you try again ?

**Comment by despiegk** [comment]
check on /root/code/github/threefoldtech/builders/builders/core/zdb/zdb.v
make example script which builds & executes the start of the docker 
then connect to it with redis client, to see it works
